# This is a basic workflow to help you get started with Actions

name: Out of office
on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]


jobs:
  autoreply:
    runs-on: ubuntu-latest
    steps:
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for opening an issue! The maintainers of this project are currently away for a few weeks, but we'll see this as soon as we can :)"
          pr-message: "Thanks for opening an issue! The maintainers of this project are currently away for a few weeks, but we'll see this as soon as we can :)"
          footer: "From the Data Hazards team!"
